/*
 * File: app/controller/Audio.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('MyApp.controller.Audio', {
    extend: 'Ext.app.Controller',

    config: {

    },

    playPong: function() {
        var audio = Ext.ComponentQuery.query('#Sound')[0].down('#pong');

        audio.play();
    },

    playCollision: function() {
        var audio = Ext.ComponentQuery.query('#Sound')[0].down('#collision');

        audio.play();
    },

    playWin: function() {
        var audio = Ext.ComponentQuery.query('#Sound')[0].down('#win');

        audio.play();
    },

    playLose: function() {
        var audio = Ext.ComponentQuery.query('#Sound')[0].down('#lose');

        audio.play();
    }

});