/*
 * File: app/controller/Ball.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('MyApp.controller.Ball', {
    extend: 'Ext.app.Controller',

    config: {

    },

    checkCollisions: function(ball) {
        var leftPaddle  = MyApp.app.paddleLeft.element.getBox(),
            rightPaddle = MyApp.app.paddleRight.element.getBox(),
            ballBox     = ball.getBox(),
            ballHeight  = ball.getHeight(),
            collisionX  = false,
            collisionY  = false,
            surfaceBox;

        if (!MyApp.app.surface) { 
            MyApp.app.surface = Ext.ComponentQuery.query('viewport > panel')[0].element.down('.x-panel-inner'); 
        }
        surfaceBox = MyApp.app.surface.getBox();

        //check collision with borders
        if (ballBox.left < surfaceBox.left) {
            MyApp.app.dispatch({
                controller : 'Referee',
                action     : 'incrementScore',
                args       : [ true ]
            });

            return false;
        }
        else if (ballBox.right > surfaceBox.right) {
            MyApp.app.dispatch({
                controller : 'Referee',
                action     : 'incrementScore',
                args       : [ false ]
            });

            return false;
        }
        if (ballBox.top < surfaceBox.top || ballBox.bottom > surfaceBox.bottom) {
            collisionY = true;
        }
        //check collision with paddles
        if (Ball.direction[0] < 0) {
            if (ballBox.bottom >= leftPaddle.top && ballBox.top <= leftPaddle.bottom) {
                if (ballBox.left <= leftPaddle.right && ballBox.left >= leftPaddle.right - Ball.speed - Ball.xConstant) { 
                    collisionX = true;
                    Ball.checkSpeed();
                    this.getDeflection(ballBox, leftPaddle);
                }
            }
        }
        else {
            if (ballBox.bottom >= rightPaddle.top && ballBox.top <= rightPaddle.bottom) {
                if (ballBox.right >= rightPaddle.left && ballBox.right <= rightPaddle.left + Ball.speed + Ball.xConstant) { 
                    collisionX = true; 
                    Ball.checkSpeed();
                    this.getDeflection(ballBox, rightPaddle);
                }
            }
        }

        //change ball direction, if necessary
        this.getDirection(collisionX, collisionY);

        return true;
    },

    update: function(ball) {
        var el  = ball.element,
            pos = el.getXY(),
            xy = Ball.getXY(pos);

        el.setXY(xy);
        MyApp.controller.Paddle.prototype.updateCPU(xy);

        //check XY coordinates to see if player has scored
        this.checkCollisions(el);
    },

    getDirection: function(collisionX, collisionY) {
        if (collisionX) { 
            Ball.direction[0] *= -1; 
            Ball.vollies++;
        }
        if (collisionY) { Ball.direction[1] *= -1; }
    },

    getDeflection: function(ball, paddle) {
        var ballMiddle = ball.top + (ball.height / 2),
            paddleSection = paddle.height / 5;

        if (ballMiddle <= paddle.top + paddleSection || ballMiddle >= paddle.bottom - paddleSection) {
            Ball.angle = Ball.angles.high;
            return;
        }

        paddleSection *= 2;

        if (ballMiddle <= paddle.top + paddleSection || ballMiddle >= paddle.bottom - paddleSection) {
            Ball.angle = Ball.angles.mid;
            return;
        }

        Ball.angle = Ball.angles.low;
        Ball.resetSpeed(); //only an low angle returns
        return;
    }

});