/*
 * File: app/controller/Paddle.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('MyApp.controller.Paddle', {
    extend: 'Ext.app.Controller',

    config: {

    },

    updateCPU: function(xy) {
        //TODO: Add some AI by randomizing XY position according to difficulty
        MyApp.app.paddleLeft.element.setXY(xy);
    }

});