/*
 * File: app/controller/Referee.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('MyApp.controller.Referee', {
    extend: 'Ext.app.Controller',

    config: {
        control: {
            "button#playpause": {
                tap: 'playPause'
            },
            "sliderfield": {
                change: 'setDifficulty'
            }
        }
    },

    incrementScore: function(isPlayer) {
        MyApp.app.stopGame();

        if (!this.scoreCPU) { this.scoreCPU = 0; }
        if (!this.scorePlayer) { this.scorePlayer = 0; }

        if (isPlayer) {
            Ext.ComponentQuery.query('#scorePlayer')[0].setHtml('Player: ' + ++this.scorePlayer);
        }
        else {
            Ext.ComponentQuery.query('#scoreCPU')[0].setHtml('CPU: ' + ++this.scoreCPU);
        }

        //if score is less than X, restart game
        if (this.scoreCPU < 10 && this.scorePlayer < 10) {
            var box = MyApp.app.surface.getBox();

            //center the ball
            MyApp.app.ball.element.setXY(
            [ Math.floor(box.width / 2), Math.floor( box.height / 2) ]
            );

            MyApp.app.startGame();
        }
        else if (this.scoreCPU === 10) {
            Ext.Msg.alert('Winner', 'The CPU wins!');
        }
        else {
            Ext.Msg.alert('Winner', 'You win!');
        }
    },

    playPause: function(button, e, options) {
        if (MyApp.intervalID) { MyApp.app.stopGame(); }
        else { MyApp.app.startGame(); }
    },

    setDifficulty: function(slider, value, options) {
        MyApp.app.difficulty = slider.getValue()[0];

        //var paddleLeft  = Ext.ComponentQuery.query('#cpu')[0];
        //paddleLeft.setHeight(20 * MyApp.app.difficulty);
    }

});